import { join } from "path";

export const PROJECT_ROOT = join(import.meta.dir, "..", "..");
export const DATA_ROOT = join(PROJECT_ROOT, "data");
export const WEB_PUBLIC_DATA_ROOT = join(PROJECT_ROOT, "web", "public", "data");

export const BUNDLE_VERSIONS: Record<string, number> = {
  tanaj: 1,
  besorah: 1,
  dss: 1,
  dictionary: 2,
  tth: 1,
  ts2009: 1,
  hutter: 1,
};

// Canonical 66-book order for deterministic metadata sorting.
export const CANONICAL_BOOK_ORDER = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Samuel1",
  "Samuel2",
  "Kings1",
  "Kings2",
  "Isaiah",
  "Jeremiah",
  "Ezekiel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Psalms",
  "Proverbs",
  "Job",
  "SongOfSolomon",
  "Ruth",
  "Lamentations",
  "Ecclesiastes",
  "Esther",
  "Daniel",
  "Ezra",
  "Nehemiah",
  "Chronicles1",
  "Chronicles2",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "Corinthians1",
  "Corinthians2",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "Thessalonians1",
  "Thessalonians2",
  "Timothy1",
  "Timothy2",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "Peter1",
  "Peter2",
  "John1",
  "John2",
  "John3",
  "Jude",
  "Revelation",
] as const;

export const OE_TO_ENGLISH: Record<string, string> = {
  genesis: "Genesis",
  exodus: "Exodus",
  leviticus: "Leviticus",
  numbers: "Numbers",
  deuteronomy: "Deuteronomy",
  joshua: "Joshua",
  judges: "Judges",
  isamuel: "Samuel1",
  iisamuel: "Samuel2",
  ikings: "Kings1",
  iikings: "Kings2",
  isaiah: "Isaiah",
  jeremiah: "Jeremiah",
  ezekiel: "Ezekiel",
  hosea: "Hosea",
  joel: "Joel",
  amos: "Amos",
  obadiah: "Obadiah",
  jonah: "Jonah",
  micah: "Micah",
  nahum: "Nahum",
  habakkuk: "Habakkuk",
  zephaniah: "Zephaniah",
  haggai: "Haggai",
  zechariah: "Zechariah",
  malachi: "Malachi",
  psalms: "Psalms",
  proverbs: "Proverbs",
  job: "Job",
  songofsolomon: "SongOfSolomon",
  ruth: "Ruth",
  lamentations: "Lamentations",
  ecclesiastes: "Ecclesiastes",
  esther: "Esther",
  daniel: "Daniel",
  ezra: "Ezra",
  nehemiah: "Nehemiah",
  ichronicles: "Chronicles1",
  iichronicles: "Chronicles2",
};

export const DELITZSCH_TO_ENGLISH: Record<string, string> = {
  matthew: "Matthew",
  mark: "Mark",
  luke: "Luke",
  john: "John",
  acts: "Acts",
  romans: "Romans",
  corinthians1: "Corinthians1",
  corinthians2: "Corinthians2",
  galatians: "Galatians",
  ephesians: "Ephesians",
  philippians: "Philippians",
  colossians: "Colossians",
  thessalonians1: "Thessalonians1",
  thessalonians2: "Thessalonians2",
  timothy1: "Timothy1",
  timothy2: "Timothy2",
  titus: "Titus",
  philemon: "Philemon",
  hebrews: "Hebrews",
  james: "James",
  peter1: "Peter1",
  peter2: "Peter2",
  john1: "John1",
  john2: "John2",
  john3: "John3",
  jude: "Jude",
  revelation: "Revelation",
};
