default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("PGHOST", "127.0.0.1") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("USER", "postgres")) %>
development:
  <<: *default
  database: davar_v2_development
test:
  <<: *default
  database: davar_v2_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
