#!/usr/bin/env python3
"""
TTH2 Configuration Module
=========================

Configuration constants and dictionaries for TTH2 processing.
Contains book information and Hebrew terms dictionaries extracted from the
original TTH processor.

Author: Davar Project
"""

# Book information database
BOOKS_INFO = {
    'bereshit': {
        'tth_name': 'Bereshit',
        'hebrew_name': 'בראשית',
        'english_name': 'Genesis',
        'spanish_name': 'Génesis',
        'book_code': 'genesis',
        'expected_chapters': 50,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'patterns': [
            r'TORAH\s*-\s*BERESHIT.*?בראשית',
            r'__TORAH\s*-\s*BERESHIT.*?בראשית__',
            r'BERESHIT.*?בראשית',
            r'בראשית',
        ],
    },
    'shemot': {
        'tth_name': 'Shemot',
        'hebrew_name': 'שמות',
        'english_name': 'Exodus',
        'spanish_name': 'Éxodo',
        'book_code': 'exodus',
        'expected_chapters': 40,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'patterns': [
            r'SHEMOT.*?שמות',
            r'__SHEMOT.*?שמות__',
            r'שמות',
        ],
    },
    'vaikra': {
        'tth_name': 'Vaikra',
        'hebrew_name': 'ויקרא',
        'english_name': 'Leviticus',
        'spanish_name': 'Levítico',
        'book_code': 'leviticus',
        'expected_chapters': 27,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'patterns': [
            r'VAIKRÁ.*?ויקרא',
            r'__VAIKRÁ.*?ויקרא__',
            r'ויקרא',
        ],
    },
    'bamidbar': {
        'tth_name': 'Bamidbar',
        'hebrew_name': 'במדבר',
        'english_name': 'Numbers',
        'spanish_name': 'Números',
        'book_code': 'numbers',
        'expected_chapters': 36,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'patterns': [
            r'BAMIDBAR.*?במדבר',
            r'__BAMIDBAR.*?במדבר__',
            r'במדבר',
        ],
    },
    'devarim': {
        'tth_name': 'Devarim',
        'hebrew_name': 'דברים',
        'english_name': 'Deuteronomy',
        'spanish_name': 'Deuteronomio',
        'book_code': 'deuteronomy',
        'expected_chapters': 34,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'patterns': [
            r'DEVARIM.*?דברים',
            r'__DEVARIM.*?דברים__',
            r'דברים',
        ],
    },
    'iehoshua': {
        'tth_name': 'Iehoshúa',
        'hebrew_name': 'יהושע',
        'english_name': 'Joshua',
        'spanish_name': 'Josué',
        'book_code': 'joshua',
        'expected_chapters': 24,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IEHOSHÚA.*?יהושע',
            r'NEVIÍM\s*-\s*IEHOSHÚA.*?יהושע',
            r'__NEVIÍM\s*-\s*IEHOSHÚA.*?יהושע__',
            r'יהושע',
        ],
    },
    'shoftim': {
        'tth_name': 'Shoftim',
        'hebrew_name': 'שפטים',
        'english_name': 'Judges',
        'spanish_name': 'Jueces',
        'book_code': 'judges',
        'expected_chapters': 21,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'SHOFTÍM.*?שפטים',
            r'__SHOFTÍM.*?שפטים__',
            r'שפטים',
        ],
    },
    'shemuel_alef': {
        'tth_name': 'Shemuel Alef',
        'hebrew_name': 'א שמואל',
        'english_name': '1 Samuel',
        'spanish_name': '1 Samuel',
        'book_code': '1_samuel',
        'expected_chapters': 31,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'SHEMUEL\s*ALEF.*?א\s*שמואל',
            r'__SHEMUEL\s*ALEF.*?א\s*שמואל__',
            r'א\s*שמואל',
        ],
    },
    'shemuel_bet': {
        'tth_name': 'Shemuel Bet',
        'hebrew_name': 'ב שמואל',
        'english_name': '2 Samuel',
        'spanish_name': '2 Samuel',
        'book_code': '2_samuel',
        'expected_chapters': 24,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'SHEMUEL\s*BET.*?ב\s*שמואל',
            r'__SHEMUEL\s*BET.*?ב\s*שמואל__',
            r'ב\s*שמואל',
        ],
    },
    'melajim_alef': {
        'tth_name': 'Melajim Alef',
        'hebrew_name': 'א מלכים',
        'english_name': '1 Kings',
        'spanish_name': '1 Reyes',
        'book_code': '1_kings',
        'expected_chapters': 22,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'MELAJIM\s*ALEF.*?א\s*מלכים',
            r'__MELAJIM\s*ALEF.*?א\s*מלכים__',
            r'א\s*מלכים',
        ],
    },
    'melajim_bet': {
        'tth_name': 'Melajim Bet',
        'hebrew_name': 'ב מלכים',
        'english_name': '2 Kings',
        'spanish_name': '2 Reyes',
        'book_code': '2_kings',
        'expected_chapters': 25,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'MELAJIM\s*BET.*?ב\s*מלכים',
            r'__MELAJIM\s+BET.*?ב\s*מלכים__',
            r'ב\s*מלכים',
        ],
    },
    'ieshaiahu': {
        'tth_name': 'Ieshaiáhu',
        'hebrew_name': 'ישעיהו',
        'english_name': 'Isaiah',
        'spanish_name': 'Isaías',
        'book_code': 'isaiah',
        'expected_chapters': 66,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IESHAIÁHU.*?ישעיהו',
            r'__IESHAIÁHU.*?ישעיהו__',
            r'ישעיהו',
        ],
    },
    'irmeiahu': {
        'tth_name': 'Irmeiáhu',
        'hebrew_name': 'ירמיהו',
        'english_name': 'Jeremiah',
        'spanish_name': 'Jeremías',
        'book_code': 'jeremiah',
        'expected_chapters': 52,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IRMEIÁHU.*?ירמיהו',
            r'__IRMEIÁHU.*?ירמיהו__',
            r'ירמיהו',
        ],
    },
    'iejezkel': {
        'tth_name': 'Iejezkel',
        'hebrew_name': 'יחזקאל',
        'english_name': 'Ezekiel',
        'spanish_name': 'Ezequiel',
        'book_code': 'ezekiel',
        'expected_chapters': 48,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IEJEZKEL.*?יחזקאל',
            r'__IEJEZKEL.*?יחזקאל__',
            r'יחזקאל',
        ],
    },
    'hoshea': {
        'tth_name': 'Hoshea',
        'hebrew_name': 'הושע',
        'english_name': 'Hosea',
        'spanish_name': 'Oseas',
        'book_code': 'hosea',
        'expected_chapters': 14,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'HOSHEA.*?הושע',
            r'__HOSHEA.*?הושע__',
            r'(?<![\u0590-\u05FF])הושע(?![\u0590-\u05FF])',
        ],
    },
    'ioel': {
        'tth_name': 'Ioel',
        'hebrew_name': 'יואל',
        'english_name': 'Joel',
        'spanish_name': 'Joel',
        'book_code': 'joel',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IOEL.*?יואל',
            r'__IOEL.*?יואל__',
            r'יואל',
        ],
    },
    'amos': {
        'tth_name': 'Amós',
        'hebrew_name': 'עמוס',
        'english_name': 'Amos',
        'spanish_name': 'Amós',
        'book_code': 'amos',
        'expected_chapters': 9,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'AMÓS.*?עמוס',
            r'__AMÓS.*?עמוס__',
            r'עמוס',
        ],
    },
    'ionah': {
        'tth_name': 'Ionah',
        'hebrew_name': 'יונה',
        'english_name': 'Jonah',
        'spanish_name': 'Jonás',
        'book_code': 'jonah',
        'expected_chapters': 4,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'IONAH.*?יונה',
            r'__IONAH.*?יונה__',
            r'יונה',
        ],
    },
    'micah': {
        'tth_name': 'Micah',
        'hebrew_name': 'מיכה',
        'english_name': 'Micah',
        'spanish_name': 'Miqueas',
        'book_code': 'micah',
        'expected_chapters': 7,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'MICAH.*?מיכה',
            r'__MICAH.*?מיכה__',
            r'מיכה',
        ],
    },
    'najum': {
        'tth_name': 'Najum',
        'hebrew_name': 'נחום',
        'english_name': 'Nahum',
        'spanish_name': 'Nahúm',
        'book_code': 'nahum',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'NAJUM.*?נחום',
            r'__NAJUM.*?נחום__',
            r'נחום',
        ],
    },
    'jabakuk': {
        'tth_name': 'Jabakuk',
        'hebrew_name': 'חבקוק',
        'english_name': 'Habakkuk',
        'spanish_name': 'Habacuc',
        'book_code': 'habakkuk',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'JABAKUK.*?חבקוק',
            r'__JABAKUK.*?חבקוק__',
            r'חבקוק',
        ],
    },
    'tzefaniah': {
        'tth_name': 'Tzefaniah',
        'hebrew_name': 'צפניה',
        'english_name': 'Zephaniah',
        'spanish_name': 'Sofonías',
        'book_code': 'zephaniah',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'TZEFANIAH.*?צפניה',
            r'__TZEFANIAH.*?צפניה__',
            r'צפניה',
        ],
    },
    'jagai': {
        'tth_name': 'Jagai',
        'hebrew_name': 'חגי',
        'english_name': 'Haggai',
        'spanish_name': 'Hageo',
        'book_code': 'haggai',
        'expected_chapters': 2,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'JAGAI.*?חגי',
            r'__JAGAI.*?חגי__',
            r'חגי',
        ],
    },
    'zejariah': {
        'tth_name': 'Zejariah',
        'hebrew_name': 'זכריה',
        'english_name': 'Zechariah',
        'spanish_name': 'Zacarías',
        'book_code': 'zechariah',
        'expected_chapters': 14,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'ZEJARIAH.*?זכריה',
            r'__ZEJARIAH.*?זכריה__',
            r'זכריה',
        ],
    },
    'malaji': {
        'tth_name': 'Malaji',
        'hebrew_name': 'מלאכי',
        'english_name': 'Malachi',
        'spanish_name': 'Malaquías',
        'book_code': 'malachi',
        'expected_chapters': 4,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'patterns': [
            r'MALAJI.*?מלאכי',
            r'__MALAJI.*?מלאכי__',
            r'מלאכי',
        ],
    },
    'tehilim': {
        'tth_name': 'Tehilim',
        'hebrew_name': 'תהלים',
        'english_name': 'Psalms',
        'spanish_name': 'Salmos',
        'book_code': 'psalms',
        'expected_chapters': 150,
        'section': 'ketuvim',
        'section_hebrew': 'כתובים',
        'section_english': 'Writings',
        'section_spanish': 'Escritos',
        'patterns': [
            r'KETUVIM\s*-\s*TEHILIM.*?תהלים',
            r'TEHILIM.*?תהלים',
            r'__KETUVIM\s*-\s*TEHILIM.*?תהלים__',
            r'__TEHILIM.*?תהלים__',
            r'תהלים',
        ],
    },
    'mishlei': {
        'tth_name': 'Mishlei',
        'hebrew_name': 'משלי',
        'english_name': 'Proverbs',
        'spanish_name': 'Proverbios',
        'book_code': 'proverbs',
        'expected_chapters': 31,
        'section': 'ketuvim',
        'section_hebrew': 'כתובים',
        'section_english': 'Writings',
        'section_spanish': 'Escritos',
        'patterns': [
            r'MISHLEI.*?משלי',
            r'__MISHLEI.*?משלי__',
            r'משלי',
        ],
    },
    'shir_hashirim': {
        'tth_name': 'Shir Hashirim',
        'hebrew_name': 'שיר השירים',
        'english_name': 'Song of Songs',
        'spanish_name': 'Cantares',
        'book_code': 'song_of_songs',
        'expected_chapters': 8,
        'section': 'ketuvim',
        'section_hebrew': 'כתובים',
        'section_english': 'Writings',
        'section_spanish': 'Escritos',
        'patterns': [
            r'KETUVIM\s*-\s*SHIR\s*HASHIRIM.*?שיר\s*השירים',
            r'SHIR\s*HASHIRIM.*?שיר\s*השירים',
            r'__SHIR\s*HASHIRIM.*?שיר\s*השירים__',
            r'CANTAR\s*DE\s*LOS\s*CANTARES.*?שיר\s*השירים',
            r'CANTARES.*?שיר\s*השירים',
            r'שיר\s*השירים',
        ],
    },
    'matityahu': {
        'tth_name': 'Matityáhu',
        'hebrew_name': 'מתתיהו',
        'english_name': 'Matthew',
        'spanish_name': 'Mateo',
        'book_code': 'matthew',
        'expected_chapters': 28,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'Matityáhu.*?מתתיהו',
            r'Matityahu.*?מתתיהו',
            r'__MATITYÁHU.*?מתתיהו__',
            r'MATEO.*?מתתיהו',
            r'מתתיהו',
        ],
    },
    'markos': {
        'tth_name': 'Markos',
        'hebrew_name': 'מרקוס',
        'english_name': 'Mark',
        'spanish_name': 'Marcos',
        'book_code': 'mark',
        'expected_chapters': 16,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'__MARKO\s*\(MARCOS\)__',
            r'Markos.*?מרקוס',
            r'Marko.*?מרקו',
            r'__MARKOS.*?מרקוס__',
            r'MARCOS.*?מרקוס',
            r'מרקוס',
            r'מרקו',
        ],
    },
    'lukas': {
        'tth_name': 'Lukas',
        'hebrew_name': 'לוקס',
        'english_name': 'Luke',
        'spanish_name': 'Lucas',
        'book_code': 'luke',
        'expected_chapters': 24,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'__LUKAH\s*\(LUCAS\)__',
            r'Lukas.*?לוקס',
            r'Lukah.*?לוקה',
            r'__LUKAS.*?לוקס__',
            r'LUCAS.*?לוקס',
            r'לוקס',
            r'לוקה',
        ],
    },
    'iojanan': {
        'tth_name': 'Iojanán',
        'hebrew_name': 'יוחנן',
        'english_name': 'John',
        'spanish_name': 'Juan',
        'book_code': 'john',
        'expected_chapters': 21,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'\*\*IOJANÁN\s*\(JUAN\)\*\*',
            r'__IOJANÁN\s*\(JUAN\)__',
            r'IOJANÁN\s*\(JUAN\)',
        ],
    },
    'maasei_hashlijim': {
        'tth_name': 'Maasei Hash\'lijim',
        'hebrew_name': 'מעשי השליחים',
        'english_name': 'Acts',
        'spanish_name': 'Hechos',
        'book_code': 'acts',
        'expected_chapters': 28,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'^\s*(?:__|\*\*)\s*MAASEI\s+HASH[\'’]LIJIM\s*\(?HECHOS\)?\s*(?:__|\*\*)\s*$',
            r'^\s*(?:__|\*\*)\s*MAASEI\s+HASH[\'’]LIJIM\s*(?:__|\*\*)\s*$',
            r'^\s*(?:__|\*\*)\s*HECHOS\s*\(?MAASEI\s+HASH[\'’]LIJIM\)?\s*(?:__|\*\*)\s*$',
            r'^\s*MAASEI\s+HASH[\'’]LIJIM\s*\(?HECHOS\)?\s*$',
            r'^\s*HECHOS\s*\(?MAASEI\s+HASH[\'’]LIJIM\)?\s*$',
        ],
    },
    'romanos': {
        'tth_name': 'Romanos',
        'hebrew_name': 'רומאים',
        'english_name': 'Romans',
        'spanish_name': 'Romanos',
        'book_code': 'romans',
        'expected_chapters': 16,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'ROMANOS.*?רומאים',
            r'רומאים',
        ],
    },
    'galatas': {
        'tth_name': 'Gálatas',
        'hebrew_name': 'גלטים',
        'english_name': 'Galatians',
        'spanish_name': 'Gálatas',
        'book_code': 'galatians',
        'expected_chapters': 6,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            r'G[ÁA]LATAS.*?גלטים',
            r'GALATIANS.*?גלטים',
            r'גלטים',
        ],
    },
    'sodot': {
        'tth_name': 'Sodot',
        'hebrew_name': 'סודות',
        'english_name': 'Revelation',
        'spanish_name': 'Apocalipsis',
        'book_code': 'revelation',
        'expected_chapters': 22,
        'section': 'besorah',
        'section_hebrew': 'בשורה',
        'section_english': 'Gospel',
        'section_spanish': 'Evangelio',
        'patterns': [
            # Canonical bold header from dedicated Sodot/Apocalipsis sources.
            r'^\*\*\s*SODOT\s*\\?\(APOCALIPSIS\\?\)\s*\*\*\s*סודות.*$',
            r'^__\s*SODOT\s*\\?\(APOCALIPSIS\\?\)\s*__\s*סודות.*$',
            r'^\*\*\s*APOCALIPSIS\s*\\?\(SODOT\\?\)\s*\*\*\s*סודות.*$',
            r'^__\s*APOCALIPSIS\s*\\?\(SODOT\\?\)\s*__\s*סודות.*$',
            r'^\*\*\s*SODOT\s*\\?\(APOCALIPSIS\\?\)\s*\*\*.*$',
            r'^__\s*SODOT\s*\\?\(APOCALIPSIS\\?\)\s*__.*$',

            # Plain header variant produced by some DOCX conversions.
            # Intentionally anchored to end-of-line to avoid TOC rows like "... (Apocalipsis) 12".
            r'^Sodot\s*\\?-\s*סודות\\?\(Apocalipsis\\?\)\s*$',
        ],
    },
}

# Hebrew terms dictionary
HEBREW_TERMS = {
    'יהוה': 'Tetragrámaton - Nombre de Elohim',
    'Yeshúa': 'Jesús en hebreo',
    'Mesías': 'El Ungido, Cristo',
    'Elohim': 'Dios, Poderoso',
    'Eloah': 'Singular de Elohim',
    'Elohah': 'Singular de Elohim',
    'EL': 'Versión corta de Elohim',
    'Adón': 'Señor, Amo',
    'Adonai': 'Señor, Amo',
    'Rúaj': 'Espíritu, viento, aliento',
    'Ha\'Kódesh': 'Santo',
    'Rúaj Ha\'Kódesh': 'Espíritu de Santidad',
    'emunah': 'fe, fidelidad, constancia',
    'shalom': 'paz, bienestar completo',
    'Ha\'Satán': 'El adversario',
    'Ha\'satán': 'El adversario',
    'Kadosh': 'Apartado, Santo',
    'Teshuváh': 'Retorno, arrepentimiento',
    'Malajim': 'Mensajeros, ángeles',
    'malaj': 'mensajero, ángel',
    'Tzebaot': 'Ejércitos',
    'Hejal': 'Santuario, Templo',
    'Ierushaláim': 'Jerusalén',
    'Ierushalem': 'Jerusalén',
    'Iehudáh': 'Judá',
    'Iehudí': 'Judío',
    'Iehudim': 'Judíos',
    'iehudim': 'Judíos',
    'Mitzráim': 'Egipto',
    'mitzrim': 'Egipcios',
    'mitzrit': 'Egipcia',
    'Shofar': 'Cuerno de carnero',
    'shofarot': 'Cuernos de carnero (plural)',
    'Gei Hinom': 'Valle de Hinom, Gehena',
    'Guei Hinom': 'Valle de Hinom, Gehena',
    'Iojanán': 'Juan',
    'Iaacob': 'Santiago, Jacobo',
    'Moshéh': 'Moisés',
    'Rajab': 'Rahab',
    'Rujot': 'Espíritus, Vientos (plural)',
    'Galil': 'Galilea',
    'Iardén': 'Jordán',
    'Bet Léjem': 'Belén',
    'Natzrat': 'Nazaret',
    'Notzrí': 'Nazareno',
    'Pésaj': 'Pascua',
    'tefilah': 'oración',
    'Ben Ha\'Adam': 'Hijo del Hombre',
    'av': 'Padre',
    'olam': 'mundo, era, tiempo',
    'man': 'Maná',
    'Rabí': 'Rabino, Maestro',
    'perushim': 'Fariseos',
    'tzadikim': 'Saduceos',
    'shomroní': 'Samaritano',
    'guelilí': 'Galileo',
    'Ieshaiáhu': 'Isaías',
    'Irmiáh': 'Jeremías',
    'Ionah': 'Jonás',
    'Eliyáhu': 'Elías',
    'Shelomóh': 'Salomón',
    'Migdalit': 'Magdalena',
    'kirení': 'Cireneo',
    'Gólgota': 'Gólgota',
    'Gulgolet': 'Calavera',
    'goral': 'suerte, suertes',
    'Matzot': 'Pan sin levadura',
    'Ish-Kariot': 'Iscariote',
    'Bet Aniah': 'Betania',
    'Eleazar': 'Lázaro',
    'Martah': 'Marta',
    'Miriam': 'María',
    'Filipos': 'Felipe',
    'Andreas': 'Andrés',
    'Shimón': 'Simón',
    'Kefa': 'Pedro',
    'Tomáh': 'Tomás',
    'Zekariáhu': 'Zacarías',
    'Adam': 'Hombre, ser humano',
    'Adamáh': 'Tierra, suelo',
    'Néfesh': 'Alma, persona, garganta',
    'Neshamáh': 'Aliento de vida',
    'jai': 'Vida',
    'najash': 'Serpiente',
    'Ishmael': 'El escucha',
    'Itzjak': 'Reirá',
    'Ribkah': 'Unida',
    'Esav': 'Peludo',
    'Iosef': 'Él añadirá',
    'Káin': 'Adquirido',
    'Hével': 'Vapor',
    'Nóaj': 'El que porta descanso',
    'Shem': 'Nombre',
    'Jam': 'Caliente',
    'Iáfet': 'Ampliar',
    'Kenáan': 'Canaán',
    'Beersheva': 'Pozo del juramento',
    'Shabat': 'Descanso, sábado',
    'Torah': 'Instrucción, ley',
    'Mishkán': 'Tabernáculo',
    'leviím': 'Levitas',
    'Mishpat': 'Juicio, proceso legal',
    'Tzedakáh': 'Justicia',
    'Jésed': 'Bondad, misericordia',
    'ketuvim': 'Escrituras',
    'kedoshim': 'Santos, apartados',
}
